# Generated by Django 5.2.14 on 2026-05-19 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('individual', 'Физическое лицо'), ('legal_entity', 'Юридическое лицо')], default='individual', max_length=20, verbose_name='Тип клиента')),
                ('telegram_chat_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Telegram chat_id')),
                ('telegram_username', models.CharField(blank=True, max_length=128, verbose_name='Username')),
                ('telegram_first_name', models.CharField(blank=True, max_length=128, verbose_name='Имя в Telegram')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('registration_address', models.TextField(blank=True, verbose_name='Адрес регистрации / юридический адрес')),
                ('last_name', models.CharField(blank=True, max_length=128, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=128, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=128, verbose_name='Отчество')),
                ('passport_series', models.CharField(blank=True, max_length=10, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=20, verbose_name='Номер паспорта')),
                ('passport_issued_by', models.CharField(blank=True, max_length=512, verbose_name='Кем выдан')),
                ('passport_issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('passport_department_code', models.CharField(blank=True, max_length=20, verbose_name='Код подразделения')),
                ('inn_individual', models.CharField(blank=True, max_length=12, verbose_name='ИНН физлица (12 знаков)')),
                ('company_name', models.CharField(blank=True, max_length=512, verbose_name='Полное наименование')),
                ('company_short_name', models.CharField(blank=True, max_length=255, verbose_name='Краткое наименование')),
                ('inn_legal', models.CharField(blank=True, max_length=10, verbose_name='ИНН (10 знаков)')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП (9 знаков)')),
                ('ogrn', models.CharField(blank=True, max_length=13, verbose_name='ОГРН (13 знаков)')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Банк')),
                ('bik', models.CharField(blank=True, max_length=9, verbose_name='БИК')),
                ('correspondent_account', models.CharField(blank=True, max_length=20, verbose_name='Корреспондентский счёт')),
                ('settlement_account', models.CharField(blank=True, max_length=20, verbose_name='Расчётный счёт')),
                ('director_name', models.CharField(blank=True, help_text='Пример: Генерального директора Иванова И.И.', max_length=255, verbose_name='ФИО руководителя (родительный падеж)')),
                ('acting_on_basis', models.CharField(blank=True, help_text='Устав, Доверенность № … и т.п.', max_length=255, verbose_name='Действует на основании')),
                ('is_lead', models.BooleanField(default=False, verbose_name='Лид')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='bot.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='client_docs/%Y/%m/', verbose_name='Файл')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('telegram_file_id', models.CharField(blank=True, max_length=255, verbose_name='Telegram file_id')),
                ('description', models.TextField(blank=True, verbose_name='Описание / подпись')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bot.contact', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Документ клиента',
                'verbose_name_plural': 'Документы клиентов',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'От клиента'), ('out', 'От менеджера')], default='in', max_length=3, verbose_name='Направление')),
                ('text', models.TextField(verbose_name='Текст')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bot.contact', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена (грн.)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='bot.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('template_file', models.FileField(help_text='Docx-файл с плейсхолдерами в формате {{ field_name }}', upload_to='templates/', verbose_name='Файл шаблона (.docx)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='bot.product', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
            },
        ),
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Telegram chat_id')),
                ('step', models.CharField(default='start', max_length=64, verbose_name='Шаг диалога')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Временные данные')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.product', verbose_name='Выбранная услуга')),
            ],
            options={
                'verbose_name': 'Состояние диалога',
                'verbose_name_plural': 'Состояния диалогов',
            },
        ),
    ]
