# Generated by Django 5.2.14 on 2026-05-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, default='', help_text='Примеры: 1500, от 1000, договорная', max_length=100, verbose_name='Цена (грн.)'),
            preserve_default=False,
        ),
    ]
