# Generated by Django 5.2.14 on 2026-06-20 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='generated/%Y/%m/', verbose_name='Готовый документ')),
                ('sent_to_client', models.BooleanField(default=False, verbose_name='Отправлен клиенту')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='bot.contact', verbose_name='Контакт')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сгенерировал')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='bot.documenttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Сгенерированный документ',
                'verbose_name_plural': 'Сгенерированные документы',
                'ordering': ['-created_at'],
            },
        ),
    ]
